version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    environment:
      POSTGRES_DB: cars     # Имя базы данных
      POSTGRES_USER: kostya        # Имя пользователя для подключения
      POSTGRES_PASSWORD: 1234    # Пароль для подключения
    ports:
      - "5432:5432"                       # Проброс порта для подключения к БД
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Для сохранения данных между перезапусками контейнера

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my_pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  # Логин для входа в pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin123      # Пароль для входа в pgAdmin
    ports:
      - "80:80"  # Проброс порта для доступа к pgAdmin через браузер
    depends_on:
      - postgres  # pgAdmin будет запускаться только после запуска PostgreSQL
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # Для сохранения данных pgAdmin между перезапусками

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local