spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cars
    username: kostya
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true   # Форматирование SQL-запросов для читаемости
        highlight_sql: true # Подсветка SQL-запросов (в Spring Boot 3)
  logging:
    level:
      org:
        hibernate: DEBUG    # Логирование работы Hibernate
        springframework: INFO  # Логирование Spring Framework
        springframework.web: DEBUG # Логирование HTTP-запросов

server:
  port: 8000